# Root of your project
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp\\main.exe"

  # 👇 Include all internal folders so Air watches them
  include_dir = ["internal", "."]

  # Watch all Go and HTML/template files
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Ignore build outputs, vendor, etc.
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false
